# Generated by Django 2.1.3 on 2018-11-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_owener'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owener',
        ),
    ]
